name: Publish

on: push

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # - uses: ./.github/actions/get-packages/
    - run pip3 install mako --user
    - run: mkdir -p build
    - run: python3 render.py >build/index.html
    - uses: peaceiris/actions-gh-pages@v1.0.1
      env:
        PUBLISH_DIR: ./build
        PUBLISH_BRANCH: gh-pages
        ACTIONS_DEPLOY_KEY: ${{ secrets.PAGES_DEPLOY }}
