name: Publish

on: push

jobs:
  publish:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: ./run/
    - uses: peaceiris/actions-gh-pages@v1.1.0
      env:
        PUBLISH_DIR: ./build
        PUBLISH_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
