name: Publish

on: push

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: ./.github/actions/get-packages/

    - uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - run: |
        python -m pip install --upgrade pip
        pip install mako
        mkdir -p build
        echo '$HOME='$HOME
        echo '$GITHUB_WORKSPACE='$GITHUB_WORKSPACE
        ls $HOME -la
        echo ----
        ls $GITHUB_WORKSPACE -la
        python render.py >build/index.html

    - uses: peaceiris/actions-gh-pages@v1.0.1
      env:
        PUBLISH_DIR: ./build
        PUBLISH_BRANCH: gh-pages
        ACTIONS_DEPLOY_KEY: ${{ secrets.PAGES_DEPLOY }}
