name: Publish

on: push

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # - uses: ./.github/actions/get-packages/

    - uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - run: "echo \"##[set-env FOOBAR=$FOOBAR]\""
      env:
        FOOBAR: barbaz

    - run: |
        python -m pip install --upgrade pip
        pip install mako conan
        conan config set general.request_timeout=600
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        env
        # conan search '*' -r all -j packages.json
        mkdir -p build
        python render.py >build/index.html

    - uses: peaceiris/actions-gh-pages@v1.0.1
      env:
        PUBLISH_DIR: ./build
        PUBLISH_BRANCH: gh-pages
        ACTIONS_DEPLOY_KEY: ${{ secrets.PAGES_DEPLOY }}
